# Generated by Django 5.1.1 on 2026-09-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_googledriveconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='borrower_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('SALE', 'Sale'), ('DEBT', 'Debt')], max_length=10),
        ),
    ]
